spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddjtest?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  servlet:
    encoding:
      charset: UTF-8
      force: true

toss:
  payments:
    secretKey: ${TOSS_SECRET_KEY:test_sk_zXLkKEypNArWmo50nX3lmeaxYG5R}
    baseUrl: ${TOSS_BASE_URL:https://api.tosspayments.com/v1}

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 5064
